In [2]:
from tensorflow.keras.preprocessing.text import one_hot

In [3]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [4]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [5]:
## Define the vocabulary size
voc_size=10000

In [7]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[2909, 562, 1466, 3252],
 [2909, 562, 1466, 2393],
 [2909, 2983, 1466, 7746],
 [7252, 8484, 9518, 6900, 4028],
 [7252, 8484, 9518, 6900, 7036],
 [1275, 2909, 5098, 1466, 3226],
 [2323, 3097, 4282, 6900]]

In [8]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [9]:
import numpy as np

In [10]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0 2909  562 1466 3252]
 [   0    0    0    0 2909  562 1466 2393]
 [   0    0    0    0 2909 2983 1466 7746]
 [   0    0    0 7252 8484 9518 6900 4028]
 [   0    0    0 7252 8484 9518 6900 7036]
 [   0    0    0 1275 2909 5098 1466 3226]
 [   0    0    0    0 2323 3097 4282 6900]]


In [11]:
## feature representation
dim=10

In [12]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [13]:
model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [14]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 77ms/step


array([[[-3.70582715e-02, -9.84825939e-03,  4.26210873e-02,
          4.63304035e-02,  2.67946757e-02, -1.17021799e-03,
          1.47060491e-02,  3.63667868e-02,  1.01992264e-02,
         -3.42947729e-02],
        [-3.70582715e-02, -9.84825939e-03,  4.26210873e-02,
          4.63304035e-02,  2.67946757e-02, -1.17021799e-03,
          1.47060491e-02,  3.63667868e-02,  1.01992264e-02,
         -3.42947729e-02],
        [-3.70582715e-02, -9.84825939e-03,  4.26210873e-02,
          4.63304035e-02,  2.67946757e-02, -1.17021799e-03,
          1.47060491e-02,  3.63667868e-02,  1.01992264e-02,
         -3.42947729e-02],
        [-3.70582715e-02, -9.84825939e-03,  4.26210873e-02,
          4.63304035e-02,  2.67946757e-02, -1.17021799e-03,
          1.47060491e-02,  3.63667868e-02,  1.01992264e-02,
         -3.42947729e-02],
        [-4.28611524e-02,  7.34913349e-03, -4.64027636e-02,
         -4.55799215e-02,  1.61227621e-02, -2.44763847e-02,
          4.67697419e-02, -4.85993735e-02, -1.592121

In [15]:
embedded_docs[0]

array([   0,    0,    0,    0, 2909,  562, 1466, 3252])

In [19]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 18ms/step


array([[-0.03705827, -0.00984826,  0.04262109,  0.0463304 ,  0.02679468,
        -0.00117022,  0.01470605,  0.03636679,  0.01019923, -0.03429477],
       [-0.03705827, -0.00984826,  0.04262109,  0.0463304 ,  0.02679468,
        -0.00117022,  0.01470605,  0.03636679,  0.01019923, -0.03429477],
       [-0.03705827, -0.00984826,  0.04262109,  0.0463304 ,  0.02679468,
        -0.00117022,  0.01470605,  0.03636679,  0.01019923, -0.03429477],
       [-0.03705827, -0.00984826,  0.04262109,  0.0463304 ,  0.02679468,
        -0.00117022,  0.01470605,  0.03636679,  0.01019923, -0.03429477],
       [-0.04286115,  0.00734913, -0.04640276, -0.04557992,  0.01612276,
        -0.02447638,  0.04676974, -0.04859937, -0.01592121, -0.03583764],
       [-0.02475655,  0.02662004, -0.02353004, -0.00180923,  0.03796642,
        -0.00131835,  0.00040761, -0.03224515,  0.01655697,  0.03181872],
       [ 0.03340889, -0.00256362, -0.03231614, -0.0035248 , -0.01219158,
         0.03773126, -0.03450388, -0.03453695